/* Auto-generated by genmsg_cpp for file /home/mchehaid/ros_workspace/GATE_ZigBee/msg/FrameSens.msg */
#ifndef GATE_ZIGBEE_MESSAGE_FRAMESENS_H
#define GATE_ZIGBEE_MESSAGE_FRAMESENS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace GATE_ZigBee
{
template <class ContainerAllocator>
struct FrameSens_ {
  typedef FrameSens_<ContainerAllocator> Type;

  FrameSens_()
  : seq(0)
  , stamp()
  , capid()
  , caplocation()
  , sensvals()
  {
  }

  FrameSens_(const ContainerAllocator& _alloc)
  : seq(0)
  , stamp()
  , capid(_alloc)
  , caplocation(_alloc)
  , sensvals(_alloc)
  {
  }

  typedef uint32_t _seq_type;
  uint32_t seq;

  typedef ros::Time _stamp_type;
  ros::Time stamp;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _capid_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  capid;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _caplocation_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  caplocation;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sensvals_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  sensvals;


  typedef boost::shared_ptr< ::GATE_ZigBee::FrameSens_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::GATE_ZigBee::FrameSens_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct FrameSens
typedef  ::GATE_ZigBee::FrameSens_<std::allocator<void> > FrameSens;

typedef boost::shared_ptr< ::GATE_ZigBee::FrameSens> FrameSensPtr;
typedef boost::shared_ptr< ::GATE_ZigBee::FrameSens const> FrameSensConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::GATE_ZigBee::FrameSens_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::GATE_ZigBee::FrameSens_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace GATE_ZigBee

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::GATE_ZigBee::FrameSens_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::GATE_ZigBee::FrameSens_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::GATE_ZigBee::FrameSens_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3a4eba2d81702f284d03cceeefea0aac";
  }

  static const char* value(const  ::GATE_ZigBee::FrameSens_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3a4eba2d81702f28ULL;
  static const uint64_t static_value2 = 0x4d03cceeefea0aacULL;
};

template<class ContainerAllocator>
struct DataType< ::GATE_ZigBee::FrameSens_<ContainerAllocator> > {
  static const char* value() 
  {
    return "GATE_ZigBee/FrameSens";
  }

  static const char* value(const  ::GATE_ZigBee::FrameSens_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::GATE_ZigBee::FrameSens_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint32 seq\n\
time stamp\n\
string capid\n\
string caplocation\n\
string sensvals\n\
\n\
";
  }

  static const char* value(const  ::GATE_ZigBee::FrameSens_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::GATE_ZigBee::FrameSens_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.seq);
    stream.next(m.stamp);
    stream.next(m.capid);
    stream.next(m.caplocation);
    stream.next(m.sensvals);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FrameSens_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::GATE_ZigBee::FrameSens_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::GATE_ZigBee::FrameSens_<ContainerAllocator> & v) 
  {
    s << indent << "seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seq);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "capid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.capid);
    s << indent << "caplocation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.caplocation);
    s << indent << "sensvals: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sensvals);
  }
};


} // namespace message_operations
} // namespace ros

#endif // GATE_ZIGBEE_MESSAGE_FRAMESENS_H

